#!/bin/sh

chmod a+rwx /opt/saita2adfree/qml/arcade_harmattan_adfree/assets/levels/classes.xml
chmod a+rwx /opt/saita2adfree/qml/arcade_harmattan_adfree/assets/levels/advanced.xml
chmod a+rwx /opt/saita2adfree/qml/arcade_harmattan_adfree/assets/levels/basic.xml

exit 0
